
/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package loffer_shop;
import java.awt.Color;
import com.mysql.jdbc.Connection;
import com.mysql.jdbc.PreparedStatement;
import java.awt.print.PrinterException;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.HashMap;
import javax.swing.JOptionPane;
import javax.swing.JTextField;
import javax.swing.table.DefaultTableModel;


/**
 *
 * @author Master
 */
public class Menu_ReportList extends javax.swing.JFrame {

    /**
     * Creates new form Menu
     */
    int mouseX;
    int mouseY;
    PreparedStatement pst=null;
    ResultSet rs=null;
    Connection con;
    public Menu_ReportList() {
        initComponents();con=DBConnection.connect();
        salelord();
        stocklord();
        this.setBackground(new Color(0,0,0,0));
        CusAllday.setBackground(new Color(176,234,255,150));
        Sellallday.setBackground(new Color(176,234,255,150));
        perdays.setBackground(new Color(176,234,255,150));
        perdayc.setBackground(new Color(176,234,255,150));
        catday.setBackground(new Color(176,234,255,150));
        perin.setBackground(new Color(176,234,255,150));
        ClickMenu.setVisible(false);
        ClickStock.setVisible(false);
        ClickAddItem.setVisible(false);
        ClickSell.setVisible(false);
        ClickReport.setVisible(true);
    }
    private void salelord(){
    try{
            String sql ="SELECT `INID`, `Customer_Name`, `TP_number`, `address_customer`, `Total_Qty`, `Total_Bill`, `Status`, `Balance`, `date` FROM `sales`";
            pst = (PreparedStatement) con.prepareStatement(sql);
            rs=pst.executeQuery();
            tblsale.setModel(net.proteanit.sql.DbUtils.resultSetToTableModel(rs));
        } catch(SQLException e){
            JOptionPane.showMessageDialog(null, e);
        }
    
    
    }
    private void stocklord(){
    try{
            String sql ="SELECT `INID`, `Product_Name`, `Category`, `serial_no`, `qty`, `Unit_Price`, `Total_Price`, `date` FROM `cart`";
            pst = (PreparedStatement) con.prepareStatement(sql);
            rs=pst.executeQuery();
            tblstock.setModel(net.proteanit.sql.DbUtils.resultSetToTableModel(rs));
        } catch(SQLException e){
            JOptionPane.showMessageDialog(null, e);
        }
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        NameProduct = new javax.swing.JLabel();
        jPanel4 = new javax.swing.JPanel();
        jPanel5 = new javax.swing.JPanel();
        jLabel9 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jPanel6 = new javax.swing.JPanel();
        jLabel10 = new javax.swing.JLabel();
        jPanel7 = new javax.swing.JPanel();
        jLabel11 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblsale = new javax.swing.JTable();
        tdate1 = new com.toedter.calendar.JDateChooser();
        tdate = new com.toedter.calendar.JDateChooser();
        fdate = new com.toedter.calendar.JDateChooser();
        perin = new javax.swing.JButton();
        perdays = new javax.swing.JButton();
        Sellallday = new javax.swing.JButton();
        CusAllday = new javax.swing.JButton();
        txtinvoice = new javax.swing.JTextField();
        jPanel8 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        txtcategory = new javax.swing.JTextField();
        jPanel10 = new javax.swing.JPanel();
        jLabel13 = new javax.swing.JLabel();
        jPanel11 = new javax.swing.JPanel();
        jLabel18 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        tblstock = new javax.swing.JTable();
        perdayc = new javax.swing.JButton();
        catday = new javax.swing.JButton();
        tdate2 = new com.toedter.calendar.JDateChooser();
        jPanel9 = new javax.swing.JPanel();
        jLabel12 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        fdate1 = new com.toedter.calendar.JDateChooser();
        jLabel19 = new javax.swing.JLabel();
        tdate3 = new com.toedter.calendar.JDateChooser();
        Movement = new javax.swing.JLabel();
        ClickMenu = new javax.swing.JLabel();
        MainReportList = new javax.swing.JLabel();
        ClickSell = new javax.swing.JLabel();
        MainAddItem = new javax.swing.JLabel();
        ClickAddItem = new javax.swing.JLabel();
        MainMenu = new javax.swing.JLabel();
        MainSell = new javax.swing.JLabel();
        ClickReport = new javax.swing.JLabel();
        ClickStock = new javax.swing.JLabel();
        MainStock = new javax.swing.JLabel();
        Menu = new javax.swing.JLabel();
        CloseP = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        setSize(new java.awt.Dimension(1350, 800));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(222, 241, 252));
        jPanel1.setPreferredSize(new java.awt.Dimension(920, 610));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel2.setBackground(new java.awt.Color(235, 248, 255));

        NameProduct.setFont(new java.awt.Font("Tempus Sans ITC", 1, 36)); // NOI18N
        NameProduct.setForeground(new java.awt.Color(255, 153, 102));
        NameProduct.setText("Daeng Gi Meori DLAESOO");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap(197, Short.MAX_VALUE)
                .addComponent(NameProduct, javax.swing.GroupLayout.PREFERRED_SIZE, 469, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(224, 224, 224))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(NameProduct)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel1.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 11, 890, -1));

        jPanel4.setBackground(new java.awt.Color(235, 248, 255));
        jPanel4.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel5.setBackground(new java.awt.Color(222, 241, 252));
        jPanel5.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jPanel5MouseClicked(evt);
            }
        });

        jLabel9.setFont(new java.awt.Font("Tempus Sans ITC", 1, 18)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(255, 153, 102));
        jLabel9.setText("Clear");

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        jPanel4.add(jPanel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(810, 50, 60, 30));

        jLabel1.setFont(new java.awt.Font("Tempus Sans ITC", 1, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 153, 102));
        jLabel1.setText("Sales");
        jPanel4.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 11, 64, -1));

        jLabel14.setFont(new java.awt.Font("Tempus Sans ITC", 1, 18)); // NOI18N
        jLabel14.setForeground(new java.awt.Color(255, 153, 153));
        jLabel14.setText("To");
        jPanel4.add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(238, 56, -1, -1));

        jLabel15.setFont(new java.awt.Font("Tempus Sans ITC", 1, 18)); // NOI18N
        jLabel15.setForeground(new java.awt.Color(255, 153, 153));
        jLabel15.setText("Form");
        jPanel4.add(jLabel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 56, 64, -1));

        jPanel6.setBackground(new java.awt.Color(222, 241, 252));
        jPanel6.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jPanel6MouseClicked(evt);
            }
        });

        jLabel10.setFont(new java.awt.Font("Tempus Sans ITC", 1, 18)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(255, 153, 102));
        jLabel10.setText("Print");

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel6Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(20, 20, 20))
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        jPanel4.add(jPanel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(720, 50, 70, 30));

        jPanel7.setBackground(new java.awt.Color(222, 241, 252));
        jPanel7.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jPanel7MouseClicked(evt);
            }
        });

        jLabel11.setFont(new java.awt.Font("Tempus Sans ITC", 1, 18)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(255, 153, 102));
        jLabel11.setText("Process");

        javax.swing.GroupLayout jPanel7Layout = new javax.swing.GroupLayout(jPanel7);
        jPanel7.setLayout(jPanel7Layout);
        jPanel7Layout.setHorizontalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel7Layout.setVerticalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addComponent(jLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        jPanel4.add(jPanel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(620, 50, 80, 30));

        tblsale.setBackground(new java.awt.Color(235, 248, 255));
        tblsale.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {},
                {},
                {},
                {}
            },
            new String [] {

            }
        ));
        tblsale.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblsaleMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tblsale);

        jPanel4.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 106, 870, 130));

        tdate1.setDateFormatString("yyyy-MM-dd");
        tdate1.setMaxSelectableDate(new java.util.Date(253373335293000L));
        tdate1.setMaximumSize(new java.awt.Dimension(220, 30));
        tdate1.setMinSelectableDate(new java.util.Date(-62135791107000L));
        jPanel4.add(tdate1, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 56, 150, -1));

        tdate.setDateFormatString("yyyy-MM-dd");
        tdate.setMaxSelectableDate(new java.util.Date(253373335293000L));
        tdate.setMaximumSize(new java.awt.Dimension(220, 30));
        tdate.setMinSelectableDate(new java.util.Date(-62135791107000L));
        jPanel4.add(tdate, new org.netbeans.lib.awtextra.AbsoluteConstraints(271, 56, 150, -1));

        fdate.setDateFormatString("yyyy-MM-dd");
        fdate.setInheritsPopupMenu(true);
        fdate.setMaxSelectableDate(new java.util.Date(253373335288000L));
        fdate.setMaximumSize(new java.awt.Dimension(220, 30));
        fdate.setMinSelectableDate(new java.util.Date(-62135791112000L));
        jPanel4.add(fdate, new org.netbeans.lib.awtextra.AbsoluteConstraints(78, 56, 150, -1));

        perin.setFont(new java.awt.Font("Tempus Sans ITC", 1, 14)); // NOI18N
        perin.setForeground(new java.awt.Color(153, 0, 255));
        perin.setText("PER INVOICE");
        perin.setDebugGraphicsOptions(javax.swing.DebugGraphics.NONE_OPTION);
        perin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                perinActionPerformed(evt);
            }
        });
        jPanel4.add(perin, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 10, 140, 30));

        perdays.setFont(new java.awt.Font("Tempus Sans ITC", 1, 14)); // NOI18N
        perdays.setForeground(new java.awt.Color(153, 0, 255));
        perdays.setText("PER DAY");
        perdays.setDebugGraphicsOptions(javax.swing.DebugGraphics.NONE_OPTION);
        perdays.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                perdaysActionPerformed(evt);
            }
        });
        jPanel4.add(perdays, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 10, 100, 30));

        Sellallday.setFont(new java.awt.Font("Tempus Sans ITC", 1, 14)); // NOI18N
        Sellallday.setForeground(new java.awt.Color(153, 0, 255));
        Sellallday.setText("SELL ALL DAYS");
        Sellallday.setDebugGraphicsOptions(javax.swing.DebugGraphics.NONE_OPTION);
        Sellallday.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SellalldayActionPerformed(evt);
            }
        });
        jPanel4.add(Sellallday, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 10, 140, 30));

        CusAllday.setFont(new java.awt.Font("Tempus Sans ITC", 1, 14)); // NOI18N
        CusAllday.setForeground(new java.awt.Color(153, 0, 255));
        CusAllday.setText("CUSTOMER ALL DAYS");
        CusAllday.setDebugGraphicsOptions(javax.swing.DebugGraphics.NONE_OPTION);
        CusAllday.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CusAlldayActionPerformed(evt);
            }
        });
        jPanel4.add(CusAllday, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 10, -1, 30));

        txtinvoice.setBackground(new java.awt.Color(235, 248, 255));
        txtinvoice.setFont(new java.awt.Font("Tempus Sans ITC", 1, 16)); // NOI18N
        txtinvoice.setForeground(new java.awt.Color(255, 153, 153));
        txtinvoice.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtinvoiceKeyReleased(evt);
            }
        });
        jPanel4.add(txtinvoice, new org.netbeans.lib.awtextra.AbsoluteConstraints(710, 10, 160, -1));

        jPanel1.add(jPanel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 90, 890, 240));

        jPanel8.setBackground(new java.awt.Color(235, 248, 255));
        jPanel8.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2.setFont(new java.awt.Font("Tempus Sans ITC", 1, 24)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 153, 102));
        jLabel2.setText("Sales");
        jPanel8.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 11, 70, -1));

        jLabel17.setFont(new java.awt.Font("Tempus Sans ITC", 1, 18)); // NOI18N
        jLabel17.setForeground(new java.awt.Color(255, 153, 153));
        jLabel17.setText("Category");
        jPanel8.add(jLabel17, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 90, -1, -1));

        txtcategory.setBackground(new java.awt.Color(235, 248, 255));
        txtcategory.setFont(new java.awt.Font("Tempus Sans ITC", 1, 16)); // NOI18N
        txtcategory.setForeground(new java.awt.Color(255, 153, 153));
        txtcategory.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtcategoryKeyReleased(evt);
            }
        });
        jPanel8.add(txtcategory, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 90, 280, 30));

        jPanel10.setBackground(new java.awt.Color(222, 241, 252));
        jPanel10.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jPanel10MouseClicked(evt);
            }
        });

        jLabel13.setFont(new java.awt.Font("Tempus Sans ITC", 1, 18)); // NOI18N
        jLabel13.setForeground(new java.awt.Color(255, 153, 102));
        jLabel13.setText("Clear");

        javax.swing.GroupLayout jPanel10Layout = new javax.swing.GroupLayout(jPanel10);
        jPanel10.setLayout(jPanel10Layout);
        jPanel10Layout.setHorizontalGroup(
            jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel10Layout.createSequentialGroup()
                .addGap(0, 6, Short.MAX_VALUE)
                .addComponent(jLabel13, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        jPanel10Layout.setVerticalGroup(
            jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel10Layout.createSequentialGroup()
                .addComponent(jLabel13)
                .addGap(0, 5, Short.MAX_VALUE))
        );

        jPanel8.add(jPanel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(810, 50, 70, 30));

        jPanel11.setBackground(new java.awt.Color(222, 241, 252));
        jPanel11.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jPanel11MouseClicked(evt);
            }
        });

        jLabel18.setFont(new java.awt.Font("Tempus Sans ITC", 1, 18)); // NOI18N
        jLabel18.setForeground(new java.awt.Color(255, 153, 102));
        jLabel18.setText("Print");

        javax.swing.GroupLayout jPanel11Layout = new javax.swing.GroupLayout(jPanel11);
        jPanel11.setLayout(jPanel11Layout);
        jPanel11Layout.setHorizontalGroup(
            jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel11Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel18, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel11Layout.setVerticalGroup(
            jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel11Layout.createSequentialGroup()
                .addComponent(jLabel18, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        jPanel8.add(jPanel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(720, 50, 60, -1));

        tblstock.setBackground(new java.awt.Color(235, 248, 255));
        tblstock.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {},
                {},
                {},
                {}
            },
            new String [] {

            }
        ));
        tblstock.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblstockMouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(tblstock);

        jPanel8.add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 130, 870, 130));

        perdayc.setFont(new java.awt.Font("Tempus Sans ITC", 1, 14)); // NOI18N
        perdayc.setForeground(new java.awt.Color(153, 0, 255));
        perdayc.setText("PER DAY");
        perdayc.setDebugGraphicsOptions(javax.swing.DebugGraphics.NONE_OPTION);
        perdayc.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                perdaycActionPerformed(evt);
            }
        });
        jPanel8.add(perdayc, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 10, 100, 30));

        catday.setFont(new java.awt.Font("Tempus Sans ITC", 1, 14)); // NOI18N
        catday.setForeground(new java.awt.Color(153, 0, 255));
        catday.setText("CATEGORY ALL DAYS PER CATEGORY");
        catday.setDebugGraphicsOptions(javax.swing.DebugGraphics.NONE_OPTION);
        catday.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                catdayActionPerformed(evt);
            }
        });
        jPanel8.add(catday, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 10, 310, 30));

        tdate2.setDateFormatString("yyyy-MM-dd");
        tdate2.setMaxSelectableDate(new java.util.Date(253373335293000L));
        tdate2.setMaximumSize(new java.awt.Dimension(220, 30));
        tdate2.setMinSelectableDate(new java.util.Date(-62135791107000L));
        jPanel8.add(tdate2, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 56, 150, -1));

        jPanel9.setBackground(new java.awt.Color(222, 241, 252));
        jPanel9.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jPanel9MouseClicked(evt);
            }
        });

        jLabel12.setFont(new java.awt.Font("Tempus Sans ITC", 1, 18)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(255, 153, 102));
        jLabel12.setText("Process");

        javax.swing.GroupLayout jPanel9Layout = new javax.swing.GroupLayout(jPanel9);
        jPanel9.setLayout(jPanel9Layout);
        jPanel9Layout.setHorizontalGroup(
            jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel9Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel12, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel9Layout.setVerticalGroup(
            jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel9Layout.createSequentialGroup()
                .addComponent(jLabel12, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        jPanel8.add(jPanel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(620, 50, 80, 30));

        jLabel16.setFont(new java.awt.Font("Tempus Sans ITC", 1, 18)); // NOI18N
        jLabel16.setForeground(new java.awt.Color(255, 153, 153));
        jLabel16.setText("Form");
        jPanel8.add(jLabel16, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 56, 64, -1));

        fdate1.setDateFormatString("yyyy-MM-dd");
        fdate1.setInheritsPopupMenu(true);
        fdate1.setMaxSelectableDate(new java.util.Date(253373335288000L));
        fdate1.setMaximumSize(new java.awt.Dimension(220, 30));
        fdate1.setMinSelectableDate(new java.util.Date(-62135791112000L));
        jPanel8.add(fdate1, new org.netbeans.lib.awtextra.AbsoluteConstraints(78, 56, 150, -1));

        jLabel19.setFont(new java.awt.Font("Tempus Sans ITC", 1, 18)); // NOI18N
        jLabel19.setForeground(new java.awt.Color(255, 153, 153));
        jLabel19.setText("To");
        jPanel8.add(jLabel19, new org.netbeans.lib.awtextra.AbsoluteConstraints(238, 56, -1, -1));

        tdate3.setDateFormatString("yyyy-MM-dd");
        tdate3.setMaxSelectableDate(new java.util.Date(253373335293000L));
        tdate3.setMaximumSize(new java.awt.Dimension(220, 30));
        tdate3.setMinSelectableDate(new java.util.Date(-62135791107000L));
        jPanel8.add(tdate3, new org.netbeans.lib.awtextra.AbsoluteConstraints(271, 56, 150, -1));

        jPanel1.add(jPanel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 340, 890, 270));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 30, 910, 620));

        Movement.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                MovementMouseDragged(evt);
            }
        });
        Movement.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                MovementMousePressed(evt);
            }
        });
        getContentPane().add(Movement, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1210, 40));

        name.setFont(new java.awt.Font("Tempus Sans ITC", 1, 24)); // NOI18N
        name.setForeground(new java.awt.Color(255, 102, 102));
        getContentPane().add(name, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 70, 160, 60));

        ClickMenu.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Loffer/MainMenu.jpg"))); // NOI18N
        getContentPane().add(ClickMenu, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 180, -1, 60));

        MainReportList.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                MainReportListMouseClicked(evt);
            }
        });
        getContentPane().add(MainReportList, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 570, 290, 80));

        ClickSell.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Loffer/MainSell.jpg"))); // NOI18N
        getContentPane().add(ClickSell, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 480, 280, 60));

        MainAddItem.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                MainAddItemMouseClicked(evt);
            }
        });
        getContentPane().add(MainAddItem, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 380, 290, 70));

        ClickAddItem.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Loffer/MainAddItem.jpg"))); // NOI18N
        getContentPane().add(ClickAddItem, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 380, 290, 60));

        MainMenu.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                MainMenuMouseClicked(evt);
            }
        });
        getContentPane().add(MainMenu, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 180, 290, 70));

        MainSell.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                MainSellMouseClicked(evt);
            }
        });
        getContentPane().add(MainSell, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 470, 290, 70));

        ClickReport.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Loffer/MainReportList.jpg"))); // NOI18N
        getContentPane().add(ClickReport, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 580, 280, 60));

        ClickStock.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Loffer/MainStock.jpg"))); // NOI18N
        getContentPane().add(ClickStock, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 280, 280, 60));

        MainStock.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                MainStockMouseClicked(evt);
            }
        });
        getContentPane().add(MainStock, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 280, 290, 70));

        Menu.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Loffer/Menu.jpg"))); // NOI18N
        getContentPane().add(Menu, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1250, 650));

        CloseP.setMinimumSize(new java.awt.Dimension(30, 14));
        CloseP.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                ClosePMouseClicked(evt);
            }
        });
        getContentPane().add(CloseP, new org.netbeans.lib.awtextra.AbsoluteConstraints(1210, 0, 40, 30));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jPanel5MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel5MouseClicked
        ((JTextField)fdate.getDateEditor().getUiComponent()).setText("");
        ((JTextField)tdate.getDateEditor().getUiComponent()).setText("");
        ((JTextField)tdate1.getDateEditor().getUiComponent()).setText("");
        txtinvoice.setText("");
        stocklord();
    }//GEN-LAST:event_jPanel5MouseClicked

    private void jPanel6MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel6MouseClicked
        try{
            tblsale.print();
        }catch (PrinterException e){  }
    }//GEN-LAST:event_jPanel6MouseClicked

    private void jPanel7MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel7MouseClicked
        String saleFdate =((JTextField)fdate.getDateEditor().getUiComponent()).getText();
        String saleTdate =((JTextField)tdate.getDateEditor().getUiComponent()).getText();
        if(saleFdate.length()>0&& saleTdate.isEmpty()){
            try{
                String sql ="SELECT `INID`, `Customer_Name`, `TP_number`, `address_customer`, `Total_Qty`, `Total_Bill`, `Status`, `Balance`, `date` FROM `sales` where date=' "+saleFdate+" ' ";
                pst = (PreparedStatement) con.prepareStatement(sql);
                rs=pst.executeQuery();
                tblsale.setModel(net.proteanit.sql.DbUtils.resultSetToTableModel(rs));
            } catch(SQLException e){
                JOptionPane.showMessageDialog(null, e);
            }
        }
        else if (saleFdate.length()>0&&saleTdate.length()>0){
            try{
                String sql ="SELECT `INID`,`Customer_Name`, `TP_number`, `address_customer`, `Total_Qty`, `Total_Bill`, `Status`, `Balance`, `date` FROM `sales`where  date between ' "+saleFdate+" ' and ' "+saleTdate+" ' " ;
                pst = (PreparedStatement) con.prepareStatement(sql);
                rs=pst.executeQuery();
                tblsale.setModel(net.proteanit.sql.DbUtils.resultSetToTableModel(rs));
            } catch(SQLException e){
                JOptionPane.showMessageDialog(null, e);
            }
        }else
        {
            JOptionPane.showMessageDialog(null,"Select date");
        }
        try { 
            HashMap para = new HashMap();
            para.put("date", saleFdate);
            para.put("date1", saleTdate);
            ReportView r =new ReportView("src\\reports\\day_by_day.jasper", para);
            r.setVisible(true);
            } catch (Exception e) {
                JOptionPane.showMessageDialog(null,e);
        }
    }//GEN-LAST:event_jPanel7MouseClicked

    private void MovementMouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_MovementMouseDragged
        // TODO add your handling code here:
        int movementX = evt.getXOnScreen();
        int movementY = evt.getYOnScreen();
        this.setLocation(movementX-mouseX, movementY-mouseY);
    }//GEN-LAST:event_MovementMouseDragged

    private void MovementMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_MovementMousePressed
        // TODO add your handling code here:
        mouseX = evt.getX();
        mouseY = evt.getY();
    }//GEN-LAST:event_MovementMousePressed

    private void MainReportListMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_MainReportListMouseClicked
        // TODO add your handling code here:
        this.setVisible(true);
    }//GEN-LAST:event_MainReportListMouseClicked

    private void MainAddItemMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_MainAddItemMouseClicked
        // TODO add your handling code here:
        Menu_AddItem Main=new Menu_AddItem();
        Main.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_MainAddItemMouseClicked

    private void MainMenuMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_MainMenuMouseClicked
        // TODO add your handling code here:
        Menu Main=new Menu();
        Main.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_MainMenuMouseClicked

    private void MainSellMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_MainSellMouseClicked
        // TODO add your handling code here:
        Menu_MSell Main=new Menu_MSell();
        Main.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_MainSellMouseClicked

    private void MainStockMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_MainStockMouseClicked
        // TODO add your handling code here:
        Menu_Stock Main=new Menu_Stock();
        Main.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_MainStockMouseClicked

    private void ClosePMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ClosePMouseClicked
        // TODO add your handling code here:
        int dialogButton = JOptionPane.YES_NO_OPTION;
        int dialogResult = JOptionPane.showConfirmDialog(this, "Press Yes to Close Program Or Press No to Cancle", "Are you Sure?",dialogButton);
        if(dialogResult == 0) {
            LogIn Main=new LogIn();
            Main.setVisible(true);
            this.dispose();
        }
    }//GEN-LAST:event_ClosePMouseClicked

    private void CusAlldayActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CusAlldayActionPerformed
        // TODO add your handling code here:
        ReportView r = new ReportView("src\\reports\\inidreport.jasper");
        r.setVisible(true);
    }//GEN-LAST:event_CusAlldayActionPerformed

    private void SellalldayActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SellalldayActionPerformed
        // TODO add your handling code here:
        ReportView r = new ReportView("src\\reports\\reportday.jasper");
        r.setVisible(true);
    }//GEN-LAST:event_SellalldayActionPerformed

    private void perdaysActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_perdaysActionPerformed
        // TODO add your handling code here:
        String saleTdate =((JTextField)tdate1.getDateEditor().getUiComponent()).getText();
        if(saleTdate.equals(""))
        {
            JOptionPane.showMessageDialog(null,"Please insert on Dialog in date Category.");
        }
        else
            {try {
                HashMap para = new HashMap();
                para.put("date",saleTdate);  // inv_id  is ireport parameter name
                ReportView r =new ReportView("src\\reports\\reportday1.jasper", para);
                r.setVisible(true);
            } catch (Exception e) {
                JOptionPane.showMessageDialog(null, e);
            }
        }
    }//GEN-LAST:event_perdaysActionPerformed

    private void jPanel11MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel11MouseClicked
        try{
            tblstock.print();
        }catch (PrinterException e){  }
    }//GEN-LAST:event_jPanel11MouseClicked

    private void jPanel10MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel10MouseClicked
        ((JTextField)fdate1.getDateEditor().getUiComponent()).setText("");
        ((JTextField)tdate3.getDateEditor().getUiComponent()).setText("");
        ((JTextField)tdate2.getDateEditor().getUiComponent()).setText("");
        txtcategory.setText("");
        stocklord();
    }//GEN-LAST:event_jPanel10MouseClicked

    private void txtcategoryKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtcategoryKeyReleased
        String category =txtcategory.getText();
        if(txtcategory.getText().length()>0){
            try{
                String sql ="SELECT `INID`, `Product_Name`, `Category`, `serial_no`, `qty`, `Unit_Price`, `Total_Price`, `date` FROM `cart` where  category LIKE '%" +category+"%' ";
                pst = (PreparedStatement) con.prepareStatement(sql);
                rs=pst.executeQuery();
                tblstock.setModel(net.proteanit.sql.DbUtils.resultSetToTableModel(rs));
            } catch(SQLException e){
                JOptionPane.showMessageDialog(null, e);
            }
        }
        else
        {
            stocklord();
        }
    }//GEN-LAST:event_txtcategoryKeyReleased

    private void perdaycActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_perdaycActionPerformed
        // TODO add your handling code here:
        String saleTdate =((JTextField)tdate2.getDateEditor().getUiComponent()).getText();
        if(txtcategory.getText().equals(""))
        {
            JOptionPane.showMessageDialog(null,"Please insert on Dialog in text Category.");
        }
        else if(saleTdate.equals(""))
        {
            JOptionPane.showMessageDialog(null,"Please insert on Dialog in date Category.");
        }
        else{
            try {
            HashMap para = new HashMap();
            para.put("cateday", saleTdate); 
            para.put("cated", txtcategory.getText());// inv_id  is ireport parameter name
            ReportView r =new ReportView("src\\reports\\categorydays.jasper", para);
            r.setVisible(true);
            } catch (Exception e) {
                JOptionPane.showMessageDialog(null,e);
            }
        }
    }//GEN-LAST:event_perdaycActionPerformed

    private void catdayActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_catdayActionPerformed
        // TODO add your handling code here:
        if(txtcategory.getText().equals(""))
        {
            JOptionPane.showMessageDialog(null,"Please insert on Dialog in text Category.");
        }
        else{
            try {
            HashMap para = new HashMap();
            para.put("cate", txtcategory.getText());  // inv_id  is ireport parameter name
            ReportView r =new ReportView("src\\reports\\category.jasper", para);
            r.setVisible(true);
            } catch (Exception e) {
                JOptionPane.showMessageDialog(null,e);
            }
        }
    }//GEN-LAST:event_catdayActionPerformed

    private void tblstockMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblstockMouseClicked
        // TODO add your handling code here:
        String id;
        DefaultTableModel tmodel=(DefaultTableModel)tblstock.getModel();
        int selectrowindex=tblstock.getSelectedRow();
        id = (tmodel.getValueAt (selectrowindex,2).toString());
        try{
            String sql="SELECT `INID`, `Product_Name`, `Category`, `serial_no`, `qty`, `Unit_Price`, `Total_Price`, `date` FROM `cart`  WHERE Category"
                    + "='"+id+"'";
            pst=(PreparedStatement) con.prepareStatement(sql);
            rs=pst.executeQuery();
            if(rs.next()){
                txtcategory.setText(rs.getString("Category"));
            }
        }
        catch(SQLException e){
            JOptionPane.showMessageDialog(null, e);
        }
    }//GEN-LAST:event_tblstockMouseClicked

    private void perinActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_perinActionPerformed
        // TODO add your handling code here:
        if(txtinvoice.getText().equals(""))
        {
             JOptionPane.showMessageDialog(null,"Please Checked your requirement,Start at INID10000-INID1XXXX");
        }
        else
        {
            try {
                HashMap para = new HashMap();
                para.put("inv_id", txtinvoice.getText());  // inv_id  is ireport parameter name
                ReportView r =new ReportView("src\\reports\\print.jasper", para);
                r.setVisible(true);
                } catch (Exception e) {
                    JOptionPane.showMessageDialog(null, e);
                }
        }
    }//GEN-LAST:event_perinActionPerformed

    private void tblsaleMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblsaleMouseClicked
        // TODO add your handling code here:
        String id;
        DefaultTableModel tmodel=(DefaultTableModel)tblsale.getModel();
        int selectrowindex=tblsale.getSelectedRow();
        id = (tmodel.getValueAt (selectrowindex,0).toString());
        try{
            String sql="SELECT `INID`, `Customer_Name`, `TP_number`, `address_customer`, `Total_Qty`, `Total_Bill`, `Status`, `Balance`, `date` FROM `sales`  WHERE INID"
                    + "='"+id+"'";
            pst=(PreparedStatement) con.prepareStatement(sql);
            rs=pst.executeQuery();
            if(rs.next()){
                txtinvoice.setText(rs.getString("INID"));
            }
        }
        catch(SQLException e){
            JOptionPane.showMessageDialog(null, e);
        }
    }//GEN-LAST:event_tblsaleMouseClicked

    private void jPanel9MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel9MouseClicked
        // TODO add your handling code here:
        String saleFdate =((JTextField)fdate1.getDateEditor().getUiComponent()).getText();
        String saleTdate =((JTextField)tdate3.getDateEditor().getUiComponent()).getText();
        if(saleFdate.length()>0&& saleTdate.isEmpty()){
            try{
                String sql ="SELECT `INID`, `Product_Name`, `Category`, `serial_no`, `qty`, `Unit_Price`, `Total_Price`, `date` FROM `cart` where date=' "+saleFdate+" ' ";
                pst = (PreparedStatement) con.prepareStatement(sql);
                rs=pst.executeQuery();
                tblstock.setModel(net.proteanit.sql.DbUtils.resultSetToTableModel(rs));
            } catch(SQLException e){
                JOptionPane.showMessageDialog(null, e);
            }
        }
        else if (saleFdate.length()>0&&saleTdate.length()>0){
            try{
                String sql ="SELECT `INID`, `Product_Name`, `Category`, `serial_no`, `qty`, `Unit_Price`, `Total_Price`, `date` FROM `cart` where  date between ' "+saleFdate+" ' and ' "+saleTdate+" ' " ;
                pst = (PreparedStatement) con.prepareStatement(sql);
                rs=pst.executeQuery();
                tblstock.setModel(net.proteanit.sql.DbUtils.resultSetToTableModel(rs));
            } catch(SQLException e){
                JOptionPane.showMessageDialog(null, e);
            }
        }else
        {
            JOptionPane.showMessageDialog(null,"Select date");
        }
    }//GEN-LAST:event_jPanel9MouseClicked

    private void txtinvoiceKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtinvoiceKeyReleased
        // TODO add your handling code here:
        if(txtinvoice.getText().length()>9){
            txtinvoice.setText("INID10000");
             JOptionPane.showMessageDialog(null,"Please Checked your requirement,Start at INID10000-INID1XXXX");
        }
    }//GEN-LAST:event_txtinvoiceKeyReleased

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Menu_ReportList.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Menu_ReportList.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Menu_ReportList.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Menu_ReportList.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Menu_ReportList().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel ClickAddItem;
    private javax.swing.JLabel ClickMenu;
    private javax.swing.JLabel ClickReport;
    private javax.swing.JLabel ClickSell;
    private javax.swing.JLabel ClickStock;
    private javax.swing.JLabel CloseP;
    private javax.swing.JButton CusAllday;
    private javax.swing.JLabel MainAddItem;
    private javax.swing.JLabel MainMenu;
    private javax.swing.JLabel MainReportList;
    private javax.swing.JLabel MainSell;
    private javax.swing.JLabel MainStock;
    private javax.swing.JLabel Menu;
    private javax.swing.JLabel Movement;
    private javax.swing.JLabel NameProduct;
    private javax.swing.JButton Sellallday;
    private javax.swing.JButton catday;
    private com.toedter.calendar.JDateChooser fdate;
    private com.toedter.calendar.JDateChooser fdate1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel10;
    private javax.swing.JPanel jPanel11;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JPanel jPanel8;
    private javax.swing.JPanel jPanel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    public static final javax.swing.JLabel name = new javax.swing.JLabel();
    private javax.swing.JButton perdayc;
    private javax.swing.JButton perdays;
    private javax.swing.JButton perin;
    private javax.swing.JTable tblsale;
    private javax.swing.JTable tblstock;
    private com.toedter.calendar.JDateChooser tdate;
    private com.toedter.calendar.JDateChooser tdate1;
    private com.toedter.calendar.JDateChooser tdate2;
    private com.toedter.calendar.JDateChooser tdate3;
    private javax.swing.JTextField txtcategory;
    private javax.swing.JTextField txtinvoice;
    // End of variables declaration//GEN-END:variables
}
