
/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package loffer_shop;
import java.awt.Color;
import java.sql.Connection;
import javax.swing.JOptionPane;
import com.mysql.jdbc.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.util.Vector;
import javax.swing.table.DefaultTableModel;


/**
 *
 * @author Master
 */
public class Menu_Cancle extends javax.swing.JFrame {

    /**
     * Creates new form Menu
     */
    int mouseX;
    int mouseY;
    Connection coon;
    PreparedStatement pst=null;
    ResultSet rs=null;
    String id;
    public Menu_Cancle() {
        initComponents();coon=DBConnection.connect();
        saleload();
        cartload();
        this.setBackground(new Color(0,0,0,0));
        jButton5.setBackground(new Color(176,234,255,150));
        btDelete.setBackground(new Color(176,234,255,150));
        jButton6.setBackground(new Color(176,234,255,150));
        ClickMenu.setVisible(false);
        ClickStock.setVisible(false);
        ClickAddItem.setVisible(false);
        ClickSell.setVisible(true);
        ClickReport.setVisible(false);
    }
    private void cartload(){
    try{
            String sql ="SELECT `INID`, `Product_Name`, `Category`, `serial_no`, `qty`, `Unit_Price`, `Total_Price`, `date` FROM `cart`";
            pst = (PreparedStatement) coon.prepareStatement(sql);
            rs=pst.executeQuery();
            tblcart.setModel(net.proteanit.sql.DbUtils.resultSetToTableModel(rs));
        } catch(SQLException e){
            JOptionPane.showMessageDialog(this, e);
        }
    }
    private void saleload(){
    try{
            String sql ="SELECT `INID`, `Customer_Name`, `TP_number`, `address_customer`, `Total_Qty`, `Total_Bill`, `Status`, `Balance`, `date` FROM `sales`";
            pst = (PreparedStatement) coon.prepareStatement(sql);
            rs=pst.executeQuery();
            tbl_sale.setModel(net.proteanit.sql.DbUtils.resultSetToTableModel(rs));
        } catch(SQLException e){
            JOptionPane.showMessageDialog(this, e);
        }
    }
    private void clearData(){
        txtid.setText("");
        txtcategory.setText("");
        txtname.setText("");
        txtserial_no.setText("");
        txtcategory.setText("");
        txtuprice.setText("");
        txtQuantity.setText("");
        txttotalPrice.setText("");
        txtcategory.setText("");
        txtdate.setText("");
        CustomerS.setText("");
        saleload();
        cartload();
    }

    private void getData(){
        id=txtid.getText();
    }
    private void itemload (){
     try{
            String sql="SELECT `INID`, `Product_Name`, `Category`, `serial_no`, `qty`, `Unit_Price`, `Total_Price`, `date` FROM `cart` WHERE INID ='"+txtid.getText()+"'";
            pst=(PreparedStatement) coon.prepareStatement(sql);
            rs=pst.executeQuery();
            if(rs.next()){
                txtid.setText(rs.getString("INID"));
                txtcategory.setText(rs.getString("Category"));
                txtname.setText(rs.getString("Product_Name"));
                txtserial_no.setText(rs.getString("serial_no"));
                txtuprice.setText(rs.getString("Unit_Price"));
            }
        }
        catch(SQLException e){
            JOptionPane.showMessageDialog(null, e);
        }
         try{
            String sql="SELECT `INID`, `Total_Qty`, `Total_Bill`,`date` FROM `sales` WHERE INID ='"+txtid.getText()+"'";
            pst=(PreparedStatement) coon.prepareStatement(sql);
            rs=pst.executeQuery();
            if(rs.next()){
                txtid.setText(rs.getString("INID"));
                txtQuantity.setText(rs.getString("Total_Qty"));
                txttotalPrice.setText(rs.getString("Total_Bill"));
                txtdate.setText(rs.getString("date"));
            }
        }
        catch(SQLException e){
            JOptionPane.showMessageDialog(null, e);
        }
    }    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jButton6 = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jButton5 = new javax.swing.JButton();
        btDelete = new javax.swing.JButton();
        txtid = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        txtdate = new javax.swing.JTextField();
        txtcategory = new javax.swing.JTextField();
        txtname = new javax.swing.JTextField();
        txtserial_no = new javax.swing.JTextField();
        txtuprice = new javax.swing.JTextField();
        txtQuantity = new javax.swing.JTextField();
        txttotalPrice = new javax.swing.JTextField();
        jLabel12 = new javax.swing.JLabel();
        CustomerS = new javax.swing.JTextField();
        jScrollPane2 = new javax.swing.JScrollPane();
        tbl_sale = new javax.swing.JTable();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblcart = new javax.swing.JTable();
        jLabel5 = new javax.swing.JLabel();
        jPanel4 = new javax.swing.JPanel();
        NameProduct = new javax.swing.JLabel();
        Movement = new javax.swing.JLabel();
        CloseP = new javax.swing.JLabel();
        ClickMenu = new javax.swing.JLabel();
        MainMenu = new javax.swing.JLabel();
        ClickStock = new javax.swing.JLabel();
        MainStock = new javax.swing.JLabel();
        ClickAddItem = new javax.swing.JLabel();
        MainAddItem = new javax.swing.JLabel();
        ClickSell = new javax.swing.JLabel();
        MainSell = new javax.swing.JLabel();
        ClickReport = new javax.swing.JLabel();
        MainReportList = new javax.swing.JLabel();
        Menu = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(235, 248, 255));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jButton6.setFont(new java.awt.Font("Tempus Sans ITC", 1, 36)); // NOI18N
        jButton6.setForeground(new java.awt.Color(153, 0, 255));
        jButton6.setText("Go Back your Sell");
        jButton6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton6ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton6, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 510, -1, -1));

        jPanel2.setBackground(new java.awt.Color(223, 248, 255));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Tempus Sans ITC", 1, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 153, 153));
        jLabel1.setText("ID ");
        jPanel2.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 10, 40, -1));

        jButton5.setFont(new java.awt.Font("Tempus Sans ITC", 1, 18)); // NOI18N
        jButton5.setForeground(new java.awt.Color(153, 0, 255));
        jButton5.setText("Clear");
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });
        jPanel2.add(jButton5, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 350, -1, -1));

        btDelete.setFont(new java.awt.Font("Tempus Sans ITC", 1, 18)); // NOI18N
        btDelete.setForeground(new java.awt.Color(153, 0, 255));
        btDelete.setText("Delete");
        btDelete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btDeleteActionPerformed(evt);
            }
        });
        jPanel2.add(btDelete, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 350, -1, -1));

        txtid.setEditable(false);
        txtid.setBackground(new java.awt.Color(235, 248, 255));
        txtid.setFont(new java.awt.Font("Tempus Sans ITC", 1, 18)); // NOI18N
        txtid.setForeground(new java.awt.Color(255, 153, 153));
        txtid.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtidKeyReleased(evt);
            }
        });
        jPanel2.add(txtid, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 10, 260, 30));

        jLabel3.setFont(new java.awt.Font("Tempus Sans ITC", 1, 18)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 153, 153));
        jLabel3.setText("Category");
        jPanel2.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 50, 80, 33));

        jLabel8.setFont(new java.awt.Font("Tempus Sans ITC", 1, 18)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(255, 153, 153));
        jLabel8.setText("Total Price");
        jPanel2.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 250, -1, -1));

        jLabel4.setFont(new java.awt.Font("Tempus Sans ITC", 1, 18)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 153, 153));
        jLabel4.setText("Quantity");
        jPanel2.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 210, -1, -1));

        jLabel9.setFont(new java.awt.Font("Tempus Sans ITC", 1, 18)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(255, 153, 153));
        jLabel9.setText("Unit Price");
        jPanel2.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 170, -1, 33));

        jLabel10.setFont(new java.awt.Font("Tempus Sans ITC", 1, 18)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(255, 153, 153));
        jLabel10.setText("Serial No");
        jPanel2.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 130, -1, 33));

        jLabel2.setFont(new java.awt.Font("Tempus Sans ITC", 1, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 153, 153));
        jLabel2.setText("Item Name");
        jPanel2.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 90, -1, 33));

        jLabel11.setFont(new java.awt.Font("Tempus Sans ITC", 1, 18)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(255, 153, 153));
        jLabel11.setText("DATE");
        jPanel2.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 290, -1, -1));

        txtdate.setEditable(false);
        txtdate.setBackground(new java.awt.Color(235, 248, 255));
        txtdate.setFont(new java.awt.Font("Tempus Sans ITC", 1, 18)); // NOI18N
        txtdate.setForeground(new java.awt.Color(255, 153, 153));
        jPanel2.add(txtdate, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 290, 260, 30));

        txtcategory.setEditable(false);
        txtcategory.setBackground(new java.awt.Color(235, 248, 255));
        txtcategory.setFont(new java.awt.Font("Tempus Sans ITC", 1, 18)); // NOI18N
        txtcategory.setForeground(new java.awt.Color(255, 153, 153));
        txtcategory.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtcategoryKeyReleased(evt);
            }
        });
        jPanel2.add(txtcategory, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 50, 260, 30));

        txtname.setEditable(false);
        txtname.setBackground(new java.awt.Color(235, 248, 255));
        txtname.setFont(new java.awt.Font("Tempus Sans ITC", 1, 18)); // NOI18N
        txtname.setForeground(new java.awt.Color(255, 153, 153));
        jPanel2.add(txtname, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 90, 260, 30));

        txtserial_no.setEditable(false);
        txtserial_no.setBackground(new java.awt.Color(235, 248, 255));
        txtserial_no.setFont(new java.awt.Font("Tempus Sans ITC", 1, 18)); // NOI18N
        txtserial_no.setForeground(new java.awt.Color(255, 153, 153));
        jPanel2.add(txtserial_no, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 130, 260, 30));

        txtuprice.setEditable(false);
        txtuprice.setBackground(new java.awt.Color(235, 248, 255));
        txtuprice.setFont(new java.awt.Font("Tempus Sans ITC", 1, 18)); // NOI18N
        txtuprice.setForeground(new java.awt.Color(255, 153, 153));
        jPanel2.add(txtuprice, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 170, 260, 30));

        txtQuantity.setEditable(false);
        txtQuantity.setBackground(new java.awt.Color(235, 248, 255));
        txtQuantity.setFont(new java.awt.Font("Tempus Sans ITC", 1, 18)); // NOI18N
        txtQuantity.setForeground(new java.awt.Color(255, 153, 153));
        txtQuantity.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtQuantityKeyReleased(evt);
            }
        });
        jPanel2.add(txtQuantity, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 210, 260, 30));

        txttotalPrice.setEditable(false);
        txttotalPrice.setBackground(new java.awt.Color(235, 248, 255));
        txttotalPrice.setFont(new java.awt.Font("Tempus Sans ITC", 1, 18)); // NOI18N
        txttotalPrice.setForeground(new java.awt.Color(255, 153, 153));
        jPanel2.add(txttotalPrice, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 250, 260, 30));

        jPanel1.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 80, 390, 400));

        jLabel12.setFont(new java.awt.Font("Tempus Sans ITC", 1, 18)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(255, 153, 153));
        jLabel12.setText("Sales Search INID : ");
        jPanel1.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 340, -1, -1));

        CustomerS.setFont(new java.awt.Font("Tekton Pro Ext", 1, 18)); // NOI18N
        CustomerS.setForeground(new java.awt.Color(255, 153, 153));
        CustomerS.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                CustomerSKeyReleased(evt);
            }
        });
        jPanel1.add(CustomerS, new org.netbeans.lib.awtextra.AbsoluteConstraints(620, 340, 240, -1));

        tbl_sale.setBackground(new java.awt.Color(223, 248, 255));
        tbl_sale.setFont(new java.awt.Font("Tempus Sans ITC", 0, 14)); // NOI18N
        tbl_sale.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {},
                {},
                {},
                {}
            },
            new String [] {

            }
        ));
        tbl_sale.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tbl_saleMouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(tbl_sale);

        jPanel1.add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 380, 480, 220));

        tblcart.setBackground(new java.awt.Color(223, 248, 255));
        tblcart.setFont(new java.awt.Font("Tempus Sans ITC", 0, 14)); // NOI18N
        tblcart.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {},
                {},
                {},
                {}
            },
            new String [] {

            }
        ));
        tblcart.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblcartMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tblcart);

        jPanel1.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 110, 480, 220));

        jLabel5.setFont(new java.awt.Font("Tempus Sans ITC", 1, 18)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 153, 153));
        jLabel5.setText("Sales");
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 70, -1, -1));

        jPanel4.setBackground(new java.awt.Color(235, 248, 255));
        jPanel4.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        NameProduct.setFont(new java.awt.Font("Tempus Sans ITC", 1, 36)); // NOI18N
        NameProduct.setForeground(new java.awt.Color(255, 153, 102));
        NameProduct.setText("Daeng Gi Meori DLAESOO");
        jPanel4.add(NameProduct, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 0, 469, 55));

        jPanel1.add(jPanel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 10, 860, 50));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 30, 910, 610));

        Movement.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                MovementMouseDragged(evt);
            }
        });
        Movement.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                MovementMousePressed(evt);
            }
        });
        getContentPane().add(Movement, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1210, 40));

        CloseP.setMinimumSize(new java.awt.Dimension(30, 14));
        CloseP.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                ClosePMouseClicked(evt);
            }
        });
        getContentPane().add(CloseP, new org.netbeans.lib.awtextra.AbsoluteConstraints(1210, 0, 40, 30));

        name.setFont(new java.awt.Font("Tempus Sans ITC", 1, 24)); // NOI18N
        name.setForeground(new java.awt.Color(255, 102, 102));
        getContentPane().add(name, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 70, 160, 60));

        ClickMenu.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Loffer/MainMenu.jpg"))); // NOI18N
        getContentPane().add(ClickMenu, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 180, -1, 60));

        MainMenu.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                MainMenuMouseClicked(evt);
            }
        });
        getContentPane().add(MainMenu, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 180, 290, 70));

        ClickStock.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Loffer/MainStock.jpg"))); // NOI18N
        getContentPane().add(ClickStock, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 280, 280, 60));

        MainStock.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                MainStockMouseClicked(evt);
            }
        });
        getContentPane().add(MainStock, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 280, 290, 70));

        ClickAddItem.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Loffer/MainAddItem.jpg"))); // NOI18N
        getContentPane().add(ClickAddItem, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 380, 290, 60));

        MainAddItem.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                MainAddItemMouseClicked(evt);
            }
        });
        getContentPane().add(MainAddItem, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 380, 290, 70));

        ClickSell.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Loffer/MainSell.jpg"))); // NOI18N
        getContentPane().add(ClickSell, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 480, 280, 60));

        MainSell.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                MainSellMouseClicked(evt);
            }
        });
        getContentPane().add(MainSell, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 470, 290, 70));

        ClickReport.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Loffer/MainReportList.jpg"))); // NOI18N
        getContentPane().add(ClickReport, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 580, 280, 60));

        MainReportList.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                MainReportListMouseClicked(evt);
            }
        });
        getContentPane().add(MainReportList, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 570, 290, 80));

        Menu.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Loffer/Menu.jpg"))); // NOI18N
        getContentPane().add(Menu, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1250, 650));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void MovementMouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_MovementMouseDragged
        // TODO add your handling code here:
        int movementX = evt.getXOnScreen();
        int movementY = evt.getYOnScreen();
        this.setLocation(movementX-mouseX, movementY-mouseY);
    }//GEN-LAST:event_MovementMouseDragged

    private void MovementMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_MovementMousePressed
        // TODO add your handling code here:
        mouseX = evt.getX();
        mouseY = evt.getY();
    }//GEN-LAST:event_MovementMousePressed

    private void ClosePMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ClosePMouseClicked
        // TODO add your handling code here:
        int dialogButton = JOptionPane.YES_NO_OPTION;
        int dialogResult = JOptionPane.showConfirmDialog(this, "Press Yes to GoBack Program Or Press No to Cancle", "Are you Sure?",dialogButton);
        if(dialogResult == 0) {
            Menu_MSell Main=new Menu_MSell();
            Main.setVisible(true);
            this.dispose();
        }
    }//GEN-LAST:event_ClosePMouseClicked

    private void MainMenuMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_MainMenuMouseClicked
        // TODO add your handling code here:
        Menu Main=new Menu();
        Main.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_MainMenuMouseClicked

    private void MainAddItemMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_MainAddItemMouseClicked
        // TODO add your handling code here:
        Menu_AddItem Main=new Menu_AddItem();
        Main.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_MainAddItemMouseClicked

    private void MainSellMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_MainSellMouseClicked
        // TODO add your handling code here:
        Menu_MSell Main=new Menu_MSell();
        Main.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_MainSellMouseClicked

    private void MainReportListMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_MainReportListMouseClicked
        // TODO add your handling code here:
        Menu_ReportList Main=new Menu_ReportList();
        Main.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_MainReportListMouseClicked

    private void MainStockMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_MainStockMouseClicked
        // TODO add your handling code here:
        Menu_Stock Main=new Menu_Stock();
        Main.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_MainStockMouseClicked

    private void btDeleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btDeleteActionPerformed
        //delete btn code
         try{
            String sql="DELETE FROM `cart` WHERE INID ='"+txtid.getText()+"'";
            pst=(PreparedStatement) coon.prepareStatement(sql);
            pst.execute();
            cartload();
            JOptionPane.showMessageDialog(this, "success");
        }catch(SQLException e){
            JOptionPane.showMessageDialog(null, e);
        }
        try{
            String sql="DELETE FROM `sales` WHERE INID ='"+txtid.getText()+"'";
            pst=(PreparedStatement) coon.prepareStatement(sql);
            pst.execute();
            saleload();
            JOptionPane.showMessageDialog(this, "success");
        }catch(SQLException e){
            JOptionPane.showMessageDialog(null, e);
        }
    }//GEN-LAST:event_btDeleteActionPerformed

    private void tblcartMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblcartMouseClicked
        String id;
        DefaultTableModel tmodel=(DefaultTableModel)tblcart.getModel();
        int selectrowindex=tblcart.getSelectedRow();
        id = (tmodel.getValueAt (selectrowindex,0).toString());
        try{
           String sql="SELECT `INID`, `Product_Name`, `Category`, `serial_no`, `qty`, `Unit_Price`, `Total_Price`, `date` FROM `cart` WHERE INID ='"+id+"'";
            pst=(PreparedStatement) coon.prepareStatement(sql);
            rs=pst.executeQuery();
            if(rs.next()){
                txtid.setText(rs.getString("INID"));
                txtcategory.setText(rs.getString("Category"));
                txtname.setText(rs.getString("Product_Name"));
                txtserial_no.setText(rs.getString("serial_no"));
                txtuprice.setText(rs.getString("Unit_Price"));
            }
        }
        catch(SQLException e){
            JOptionPane.showMessageDialog(this, e);
        }
         try{
            String sql="SELECT `INID`, `Total_Qty`, `Total_Bill`,`date` FROM `sales` WHERE INID ='"+id+"'";
            pst=(PreparedStatement) coon.prepareStatement(sql);
            rs=pst.executeQuery();
            if(rs.next()){
                txtid.setText(rs.getString("INID"));
                txtQuantity.setText(rs.getString("Total_Qty"));
                txttotalPrice.setText(rs.getString("Total_Bill"));
                txtdate.setText(rs.getString("date"));
            }
        }
        catch(SQLException e){
            JOptionPane.showMessageDialog(this, e);
        }
    }//GEN-LAST:event_tblcartMouseClicked

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
        // TODO add your handling code here:
        clearData();
    }//GEN-LAST:event_jButton5ActionPerformed

    private void jButton6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton6ActionPerformed
        // TODO add your handling code here:
            Menu_MSell Main=new Menu_MSell();
            Main.setVisible(true);
            this.dispose();
    }//GEN-LAST:event_jButton6ActionPerformed

    private void txtcategoryKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtcategoryKeyReleased
        // TODO add your handling code here:
        if(txtid.getText().length()==7){
            itemload();
            txtQuantity.requestFocus();
        }
    }//GEN-LAST:event_txtcategoryKeyReleased

    private void txtQuantityKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtQuantityKeyReleased
        // TODO add your handling code here:
        int Quantity=Integer.parseInt(txtQuantity.getText());
        double Total= (double)Quantity*Double.parseDouble(txtuprice.getText());
        txttotalPrice.setText(Total+"");
    }//GEN-LAST:event_txtQuantityKeyReleased

    private void tbl_saleMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tbl_saleMouseClicked
        // TODO add your handling code here:
        String id;
        DefaultTableModel tmodel=(DefaultTableModel)tbl_sale.getModel();
        int selectrowindex=tbl_sale.getSelectedRow();
        id = (tmodel.getValueAt (selectrowindex,0).toString());
        try{
           String sql="SELECT `INID`, `Product_Name`, `Category`, `serial_no`, `qty`, `Unit_Price`, `Total_Price`, `date` FROM `cart` WHERE INID ='"+id+"'";
            pst=(PreparedStatement) coon.prepareStatement(sql);
            rs=pst.executeQuery();
            if(rs.next()){
                txtid.setText(rs.getString("INID"));
                txtcategory.setText(rs.getString("Category"));
                txtname.setText(rs.getString("Product_Name"));
                txtserial_no.setText(rs.getString("serial_no"));
                txtuprice.setText(rs.getString("Unit_Price"));
            }
        }
        catch(SQLException e){
            JOptionPane.showMessageDialog(this, e);
        }
         try{
            String sql="SELECT `INID`, `Total_Qty`, `Total_Bill`,`date` FROM `sales` WHERE INID ='"+id+"'";
            pst=(PreparedStatement) coon.prepareStatement(sql);
            rs=pst.executeQuery();
            if(rs.next()){
                txtid.setText(rs.getString("INID"));
                txtQuantity.setText(rs.getString("Total_Qty"));
                txttotalPrice.setText(rs.getString("Total_Bill"));
                txtdate.setText(rs.getString("date"));
            }
        }
        catch(SQLException e){
            JOptionPane.showMessageDialog(this, e);
        }
    }//GEN-LAST:event_tbl_saleMouseClicked

    private void txtidKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtidKeyReleased
        // TODO add your handling code here:
        itemload();
    }//GEN-LAST:event_txtidKeyReleased

    private void CustomerSKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_CustomerSKeyReleased
        // TODO add your handling code here:
        if(CustomerS.getText().length()>0)
        {
            try{
                String sql ="SELECT `INID`, `Customer_Name`, `TP_number`, `address_customer`, `Total_Qty`, `Total_Bill`, `Status`, `Balance`, `date` FROM `sales` where INID LIKE '%"+CustomerS.getText()+"%'";
                pst = (PreparedStatement) coon.prepareStatement(sql);
                rs=pst.executeQuery();
                tbl_sale.setModel(net.proteanit.sql.DbUtils.resultSetToTableModel(rs));
            } catch(SQLException e){
                JOptionPane.showMessageDialog(this, e);
            }
            try{
                String sql ="SELECT `INID`, `Product_Name`, `Category`, `serial_no`, `qty`, `Unit_Price`, `Total_Price`, `date` FROM `cart` where INID LIKE '%"+CustomerS.getText()+"%'";
                pst = (PreparedStatement) coon.prepareStatement(sql);
                rs=pst.executeQuery();
                if(rs.next()){
                    txtid.setText(rs.getString("INID"));
                    txtcategory.setText(rs.getString("Category"));
                    txtname.setText(rs.getString("Product_Name"));
                    txtserial_no.setText(rs.getString("serial_no"));
                    txtuprice.setText(rs.getString("Unit_Price"));
                }
            } catch(SQLException e){
                JOptionPane.showMessageDialog(this, e);}
            try{
                String sql ="SELECT `INID`, `Customer_Name`, `TP_number`, `address_customer`, `Total_Qty`, `Total_Bill`, `Status`, `Balance`, `date` FROM `sales` where INID LIKE '%"+CustomerS.getText()+"%'";
                pst = (PreparedStatement) coon.prepareStatement(sql);
                rs=pst.executeQuery();
                if(rs.next()){
                    txtid.setText(rs.getString("INID"));
                    txtQuantity.setText(rs.getString("Total_Qty"));
                    txttotalPrice.setText(rs.getString("Total_Bill"));
                    txtdate.setText(rs.getString("date"));
                }
            } catch(SQLException e){
                JOptionPane.showMessageDialog(this, e);
            }
        }
        else{
            saleload();
        }
    }//GEN-LAST:event_CustomerSKeyReleased

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Menu_Cancle.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Menu_Cancle.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Menu_Cancle.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Menu_Cancle.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Menu_Cancle().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel ClickAddItem;
    private javax.swing.JLabel ClickMenu;
    private javax.swing.JLabel ClickReport;
    private javax.swing.JLabel ClickSell;
    private javax.swing.JLabel ClickStock;
    private javax.swing.JLabel CloseP;
    private javax.swing.JTextField CustomerS;
    private javax.swing.JLabel MainAddItem;
    private javax.swing.JLabel MainMenu;
    private javax.swing.JLabel MainReportList;
    private javax.swing.JLabel MainSell;
    private javax.swing.JLabel MainStock;
    private javax.swing.JLabel Menu;
    private javax.swing.JLabel Movement;
    private javax.swing.JLabel NameProduct;
    private javax.swing.JButton btDelete;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton6;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    public static final javax.swing.JLabel name = new javax.swing.JLabel();
    private javax.swing.JTable tbl_sale;
    private javax.swing.JTable tblcart;
    private javax.swing.JTextField txtQuantity;
    private javax.swing.JTextField txtcategory;
    private javax.swing.JTextField txtdate;
    private javax.swing.JTextField txtid;
    private javax.swing.JTextField txtname;
    private javax.swing.JTextField txtserial_no;
    private javax.swing.JTextField txttotalPrice;
    private javax.swing.JTextField txtuprice;
    // End of variables declaration//GEN-END:variables
}
